name: Run nox

on: [push, pull_request]

jobs:
  run-nox:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: wntrblm/nox@2022.8.7
        with:
          python-versions: "3.10 3.9 3.8 3.7"
      - run: nox
