name: Run nox

on: [push, pull_request]

jobs:
  run-nox:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - uses: actions/checkout@v3
      - uses: wntrblm/nox@2023.04.22
        with:
          python-versions: "3.10, 3.9, 3.8, 3.7"
      - run: nox
